#!/bin/bash

PIN=$(ls -d /sys/devices/platform/bcm2708_spi.0/spi_master/spi0/spi0.1/stmpe-gpio.0/gpio/gpiochip*)
PIN=${PIN:+252}

if [ -n "${1}" -o -z "${0##*-on}" -o -z "${0##*-off}" ]
then
   OPT=${1:-$0}
   STATE=${OPT//*off/0}
   STATE=${STATE//*on/1}
   STATE=${STATE//^[0-9]/}
   FORCE=1
fi

if [ -n "${PIN}" ]
then
if [ -f /sys/class/gpio/export ]
then
  if [ ! -r /sys/class/gpio/gpio${PIN}/uevent ]
  then
    echo ${PIN} > /sys/class/gpio/export
  fi

  if [ -r /sys/class/gpio/gpio${PIN}/direction ]
  then
    DIR=$(cat /sys/class/gpio/gpio${PIN}/direction)

    if [ -n "${DIR##in}" ]
    then
      echo 'in' > /sys/class/gpio/gpio${PIN}/direction
    fi

    if [ -f /sys/class/gpio/gpio${PIN}/value ]
    then
      STATUS=$(cat /sys/class/gpio/gpio${PIN}/value)
      echo 'out' > /sys/class/gpio/gpio${PIN}/direction

      if [ ${FORCE:-0} -gt 0 ]
      then
        echo "$STATE" > /sys/class/gpio/gpio${PIN}/value
      else
        if [ $STATUS -gt 0 ]
          then
	  #off
	  echo '0' > /sys/class/gpio/gpio${PIN}/value
        else
	  #on
	  echo '1' > /sys/class/gpio/gpio${PIN}/value
	fi
      fi

    else
      echo "Can't read the state of GPIO ${PIN}"
    fi
  else
    echo "Can't read the direction of GPIO ${PIN}"
  fi
else
  echo "no GPIO pins to export"
fi
else
  echo "Can't find the GPIO pin, is the device working?"
fi
